server:
  port: 8383

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/emply-jasper-db?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&useSSL=false&characterEncoding=UTF-8&characterSetResults=UTF-8&createDatabaseIfNotExist=true&serverTimezone=Asia/Dhaka

  thymeleaf:
    cache: false
    enabled: true
    suffix: .html
    prefix: classpath:/templates/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect